<?php
/**
 * Buttons Repeater Component - רכיב ריפיטר כפתורים גלובלי
 * 
 * רכיב זה יכול לשמש כל הסקשנים לניהול מספר כפתורים
 * כולל הוספה, מחיקה ועריכה של כפתורים
 */

// Default button data
$defaultButtons = isset($defaultData['buttons']) && is_array($defaultData['buttons']) 
    ? $defaultData['buttons'] 
    : [
        [
            'text' => 'קנה עכשיו',
            'link' => '/products',
            'newTab' => false,
            'style' => 'filled'
        ]
    ];

$sectionType = $sectionType ?? 'hero'; // Fallback if not set
?>

<div class="bg-gray-50 rounded-lg p-4">
    <div class="flex items-center justify-between mb-3">
        <div class="flex items-center gap-2">
            <i class="ri-links-line text-purple-600"></i>
            <h4 class="font-medium text-gray-900">כפתורים</h4>
        </div>
        <button type="button" 
                id="addButton" 
                class="px-3 py-1.5 bg-purple-600 text-white text-sm rounded-md hover:bg-purple-700 transition-colors">
            <i class="ri-add-line mr-1"></i>
            הוסף כפתור
        </button>
    </div>
    
    <!-- Global Button Spacing Settings -->
    <div class="bg-white rounded-md p-3 mb-3">
        <h5 class="text-sm font-medium text-gray-900 mb-3">הגדרות ריווח כפתורים</h5>
        
        <!-- Padding Section -->
        <div class="mb-3">
            <label class="block text-xs text-gray-600 mb-2">ריווח פנימי (px)</label>
            <div class="grid grid-cols-2 gap-2">
                <div>
                    <input type="number" id="<?php echo $sectionType; ?>ButtonPaddingTop" name="buttonPaddingTop" 
                           value="<?php echo $defaultData['buttonPaddingTop'] ?? '12'; ?>" 
                           placeholder="למעלה"
                           class="w-full px-2 py-1.5 border border-gray-300 rounded text-sm focus:outline-none focus:ring-1 focus:ring-blue-500">
                </div>
                <div>
                    <input type="number" id="<?php echo $sectionType; ?>ButtonPaddingBottom" name="buttonPaddingBottom" 
                           value="<?php echo $defaultData['buttonPaddingBottom'] ?? '12'; ?>" 
                           placeholder="למטה"
                           class="w-full px-2 py-1.5 border border-gray-300 rounded text-sm focus:outline-none focus:ring-1 focus:ring-blue-500">
                </div>
                <div>
                    <input type="number" id="<?php echo $sectionType; ?>ButtonPaddingRight" name="buttonPaddingRight" 
                           value="<?php echo $defaultData['buttonPaddingRight'] ?? '32'; ?>" 
                           placeholder="ימין"
                           class="w-full px-2 py-1.5 border border-gray-300 rounded text-sm focus:outline-none focus:ring-1 focus:ring-blue-500">
                </div>
                <div>
                    <input type="number" id="<?php echo $sectionType; ?>ButtonPaddingLeft" name="buttonPaddingLeft" 
                           value="<?php echo $defaultData['buttonPaddingLeft'] ?? '32'; ?>" 
                           placeholder="שמאל"
                           class="w-full px-2 py-1.5 border border-gray-300 rounded text-sm focus:outline-none focus:ring-1 focus:ring-blue-500">
                </div>
            </div>
        </div>
        
        <!-- Margin Section -->
        <div>
            <label class="block text-xs text-gray-600 mb-2">ריווח עליון ותחתון (px)</label>
            <div class="grid grid-cols-2 gap-2">
                <div>
                    <input type="number" id="<?php echo $sectionType; ?>ButtonMarginTop" name="buttonMarginTop" 
                           value="<?php echo $defaultData['buttonMarginTop'] ?? '0'; ?>" 
                           placeholder="למעלה"
                           class="w-full px-2 py-1.5 border border-gray-300 rounded text-sm focus:outline-none focus:ring-1 focus:ring-blue-500">
                </div>
                <div>
                    <input type="number" id="<?php echo $sectionType; ?>ButtonMarginBottom" name="buttonMarginBottom" 
                           value="<?php echo $defaultData['buttonMarginBottom'] ?? '0'; ?>" 
                           placeholder="למטה"
                           class="w-full px-2 py-1.5 border border-gray-300 rounded text-sm focus:outline-none focus:ring-1 focus:ring-blue-500">
                </div>
            </div>
        </div>
    </div>

    <div id="buttonsContainer" class="space-y-3">
        <!-- Buttons will be generated by JavaScript -->
    </div>
    
    <!-- Hidden input to store buttons data -->
    <input type="hidden" id="<?php echo $sectionType; ?>Buttons" name="buttons" value="<?php echo htmlspecialchars(json_encode($defaultButtons)); ?>">
</div>

<!-- Note: JavaScript logic moved to hero.js for better integration --> 